version: '3.8'

networks:
  veloz-network:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: veloz-postgres
    environment:
      POSTGRES_USER: veloz_admin
      POSTGRES_PASSWORD: SuperSecurePassword123
      POSTGRES_DB: pedidos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - veloz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veloz_admin -d pedidos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: lojaveloz/api-gateway:latest
    container_name: veloz-gateway
    ports:
      - "8080:8080"
    networks:
      - veloz-network
    depends_on:
      - servico-pedidos

  servico-pedidos:
    image: lojaveloz/servico-pedidos:latest
    container_name: veloz-pedidos-app
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=veloz_admin
      - DB_PASSWORD=SuperSecurePassword123
      - DB_NAME=pedidos_db
    networks:
      - veloz-network
    depends_on:
      postgres-db:
        condition: service_healthy